#!/bin/bash	


rm ../../data/sc* &
cd scripts/
wait
./../build/mobilitygenerator -s 1600 -n 3 -d 920 -f "../../data/sc" -D 1 -p 5  -X 40 -S 90 -i -500 -j 500  # -o "../temp/obs"
echo "$PWD"
wait 
python2 ../scripts/animplot.py 


